name: 'Web Screenshot'
description: 'Take a screenshot of a URL using headless Chrome'
inputs:
  url:
    description: 'URL to capture screenshot of'
    required: true
    default: 'https://google.com/'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    WSA_URL: ${{ inputs.wsa_url }}
    RUST_BACKTRACE: 1
    RUST_LOG: headless_chrome=trace