on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          url: "https://example.com/"
      - uses: actions/upload-artifact@v4
        with:
          name: screenshot_png
          path: ./screenshot.png